#!/bin/sh
# Server-side demuxing by default

LIGHTBLUE="\e[38;5;87m"
LIGHTGREEN="\e[38;5;46m"
LIGHTRED="\e[38;5;196m"
NORMAL="\e[0m"
OK="${LIGHTGREEN}OK${NORMAL}"
FAIL="${LIGHTRED}FAIL${NORMAL}"
HEADER="${LIGHTBLUE}[S45 msd]${NORMAL}\t"

source /etc/device_config

case "$1" in
	start)
		echo -ne "${HEADER}Starting MSD Daemon..." > /dev/kmsg
		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
		;;

	stop)
		echo -ne "${HEADER}Stopping MSD Daemon..." > /dev/kmsg
		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
		[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" > /dev/kmsg || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
